services:
  # Servicio de desarrollo
  spacex-web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    command: npm run dev
    profiles:
      - dev

  # Servicio de producción
  spacex-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    profiles:
      - prod

  # Servicio para testing
  spacex-web-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    command: npm run test
    profiles:
      - test
